### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by xavez** [osoc16/LeuvenLeest-API#1]
- [x] Select a license
- [x] Add the license to the repo

**Comment by JasperDR** [comment]
Added the license to the backend branch which should be merged with the master branch later today

**Comment by xavez** [comment]
@JasperDR great! Actually, if you add "fixes #1" to your commit, it would’ve close this automatically upon merging to master and pushing to origin, easier to keep track of what is / what is not implemented that way ;).

**Comment by JasperDR** [comment]
ok, i'll remember it for the next time. Thanks.
