### ISSUE TITLE
POST and PUT

### ISSUE THREAD

**Issue by pietercolpaert** [osoc16/LeuvenLeest-API#2]
Small difference: HTTP POST must behave in a way where the server chooses the identifier. It's "adding something to a resource". HTTP PUT is meant to overwrite a resource, or writing for the first time a document with an identifier chosen by the client.

I think your current API specification is using POST incorrectly?

Read more: http://restcookbook.com/HTTP%20Methods/put-vs-post/

**Comment by thibautvincent** [comment]
Changed it! Your are indeed correct
https://github.com/osoc16/LeuvenLeest-API/commit/c89604d60bbec161afaf72743328c171b1566792 and https://github.com/osoc16/LeuvenLeest-API/commit/c89604d60bbec161afaf72743328c171b1566792
