### ISSUE TITLE
No data on Leuvenleestapp.be

### ISSUE THREAD

**Issue by SerkanYildiz** [osoc16/LeuvenLeest-API#6]
There is no data with reading locations on the app. Did you run the seeder?

**Comment by SerkanYildiz** [comment]
Oh I see, there is data. But getCurrentPosition works only with https connection. When I switch to the https version of the app, then I see some data. But when I click on a location, it goes to detail/117 for example, but something weird happens: it redirects back to the homepage (the http version)

**Comment by huhu1030** [comment]
Did you log in ?

**Comment by xavez** [comment]
Thank you. @SerkanYildiz. This is a known issue with Chrome: we need to run everything over https to get location there (which is a good idea anyway).

Unfortunately, there is still a bug with running the app over https. I think we need @JasperDR @AngryMoustache  or @thibautvincent to have a look at that issue.

**Comment by SerkanYildiz** [comment]
@huhu1030 Yes I was logged in. But now it works as I see. Some image resources are loaded over http, that should be fixed because Chrome warns about that & getCurrentPosition() still will not work when there is mixed content.

**Comment by xavez** [comment]
Thanks @SerkanYildiz . Closing this issue and making a new one. That placeholder image should be loaded locally in stead of hot linked!
